# Generated by Django 3.0.2 on 2020-01-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(auto_created=True, default=None, unique=True),
            preserve_default=False,
        ),
    ]
