# Generated by Django 3.0.2 on 2020-01-15 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_auto_20200114_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='invited_user',
            field=models.ManyToManyField(blank=True, related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
